platform :ios, '6.0'

#pod路径、svn路径、本地路径，三者必须完全一致。

#私有组件
def componentsPod
    pod 'JYLibrary', :path => '../'
end

#第三方
def vendorsPod
    
end

target 'JYLibraryExample' do
    componentsPod
    vendorsPod
end
